image:
  digest: ''
  registry: ghcr.io
  repository: zcube/bitnami-compat/redis
  tag: 7.0.7-debian-11-r46
metrics:
  image:
    digest: ''
    registry: ghcr.io
    repository: zcube/bitnami-compat/redis-exporter
    tag: 1.45.0-debian-11-r46
sentinel:
  image:
    digest: ''
    registry: ghcr.io
    repository: zcube/bitnami-compat/redis-sentinel
    tag: 7.0.7-debian-11-r46
sysctl:
  image:
    digest: ''
    registry: ghcr.io
    repository: zcube/bitnami-compat/bitnami-shell
    tag: 11.0.0-debian-11-r46
volumePermissions:
  image:
    digest: ''
    registry: ghcr.io
    repository: zcube/bitnami-compat/bitnami-shell
    tag: 11.0.0-debian-11-r46

