image:
  registry: ghcr.io
  repository: zcube/bitnami-compat/discourse
  tag: 2.8.11-debian-11-r41
  digest: ""
volumePermissions:
  image:
    registry: ghcr.io
    repository: zcube/bitnami-compat/bitnami-shell
    tag: 11.0.0-debian-11-r41
    digest: ""
