image:
  digest: ''
  registry: ghcr.io
  repository: zcube/bitnami-compat/wordpress
  tag: 6.2.0-debian-11-r62
mariadb:
  image:
    digest: ''
    registry: ghcr.io
    repository: zcube/bitnami-compat/mariadb
    tag: 10.9.5-debian-11-r62
  metrics:
    image:
      digest: ''
      registry: ghcr.io
      repository: zcube/bitnami-compat/mysqld-exporter
      tag: 0.14.0-debian-11-r62
  volumePermissions:
    image:
      digest: ''
      registry: ghcr.io
      repository: zcube/bitnami-compat/bitnami-shell
      tag: 11.0.0-debian-11-r62
memcached:
  image:
    digest: ''
    registry: ghcr.io
    repository: zcube/bitnami-compat/memcached
    tag: 1.6.19-debian-11-r62
  metrics:
    image:
      digest: ''
      registry: ghcr.io
      repository: zcube/bitnami-compat/memcached-exporter
      tag: 0.11.3-debian-11-r62
  volumePermissions:
    image:
      digest: ''
      registry: ghcr.io
      repository: zcube/bitnami-compat/bitnami-shell
      tag: 11.0.0-debian-11-r62
metrics:
  image:
    digest: ''
    registry: ghcr.io
    repository: zcube/bitnami-compat/apache-exporter
    tag: 0.13.1-debian-11-r62
volumePermissions:
  image:
    digest: ''
    registry: ghcr.io
    repository: zcube/bitnami-compat/bitnami-shell
    tag: 11.0.0-debian-11-r62
