image:
  registry: ghcr.io
  repository: zcube/bitnami-compat/solr
  tag: 9.1.0-debian-11-r44
  digest: ""
volumePermissions:
  image:
    registry: ghcr.io
    repository: zcube/bitnami-compat/bitnami-shell
    tag: 11.0.0-debian-11-r44
    digest: ""
