cassandra: null
postgresql:
  image:
    digest: ''
    registry: ghcr.io
    repository: zcube/bitnami-compat/postgresql
    tag: 15.2.0-debian-11-r62
  metrics:
    image:
      digest: ''
      registry: ghcr.io
      repository: zcube/bitnami-compat/postgres-exporter
      tag: 0.12.0-debian-11-r62
  volumePermissions:
    image:
      digest: ''
      registry: ghcr.io
      repository: zcube/bitnami-compat/bitnami-shell
      tag: 11.0.0-debian-11-r62
