image:
  digest: ''
  registry: ghcr.io
  repository: zcube/bitnami-compat/rabbitmq
  tag: 3.9.27-debian-11-r50
volumePermissions:
  image:
    digest: ''
    registry: ghcr.io
    repository: zcube/bitnami-compat/bitnami-shell
    tag: 11.0.0-debian-11-r50

