revision: 30
ignores:
    - php-fpm
    - apache
    - ruby
dependencies:
    ruby:
        - fluentd
        - discourse
        - python
    node:
        - discourse
    python:
        - discourse
    brotli:
        - discourse
