revision: 53
ignores:
    - php-fpm
    - ruby
dependencies:
    brotli:
        - discourse
    node:
        - discourse
        - mastodon
    postgres-client:
        - mastodon
    python:
        - discourse
        - mastodon
    redis-client:
        - mastodon
    ruby:
        - fluentd
        - discourse
        - mastodon
        - python
