revision: 52
ignores:
    - php-fpm
    # - apache
    - ruby
dependencies:
    postgres-client:
        - mastodon
    redis-client:
        - mastodon
    brotli:
        - discourse
    node:
        - discourse
        - mastodon
    python:
        - discourse
        - mastodon
    ruby:
        - fluentd
        - discourse
        - mastodon
        - python
