revision: 46
ignores:
    - php-fpm
    - apache
    - ruby
dependencies:
    brotli:
        - discourse
    node:
        - discourse
    python:
        - discourse
    ruby:
        - fluentd
        - discourse
        - python
