# https://taskfile.dev

version: '3'

tasks:
  install:tools:
    desc: Install all optional cli tools
    dir: scripts
    cmds:
      - task: install:cobracli
      - task: install:air
    silent: true

  install:cobracli:
    desc: Install cobra-cli
    cmds:
      - go install github.com/spf13/cobra-cli@latest

  install:air:
    desc: Install a hot reloader. Watch for file changes and automatically rebuilds binary
    cmds:
      - go install github.com/cosmtrek/air@latest

  permission:
    desc: chmod +x *.sh
    cmds:
      - find ./patches/ | grep "\.sh$" | xargs -I {} git update-index --chmod=+x {}

  generate:
    desc: chmod +x *.sh
    cmds:
      - go run main.go generate
      - go run main.go generateWorkflow
      - go run main.go generateReadme

  upgrade:
    desc: upgrade all bitnami submodules
    cmds:
      - find  -maxdepth 1 -type d | grep bitnami-docker | xargs -I "{}" /bin/bash -c 'cd {} && git checkout master && git pull'
      - find  -maxdepth 1 -type d | grep bitnami-docker | xargs -I "{}" /bin/bash -c 'git add {}'
      - task: generate
      - git add README.md
      - git add .github/workflows/build-on-push.yml

