# https://taskfile.dev

version: '3'

tasks:
  install:tools:
    desc: Install all optional cli tools
    dir: scripts
    cmds:
      - task: install:cobracli
      - task: install:air
    silent: true

  install:cobracli:
    desc: Install cobra-cli
    cmds:
      - go install github.com/spf13/cobra-cli@latest

  install:air:
    desc: Install a hot reloader. Watch for file changes and automatically rebuilds binary
    cmds:
      - go install github.com/cosmtrek/air@latest

  permission:
    desc: chmod +x *.sh
    cmds:
      - docker run --rm -t --entrypoint="" -v ${PWD}:/work -w /work bitnami/git /bin/bash -c 'find ./patches/ | grep "\.sh$" | xargs -I {} git update-index --chmod=+x {}'

  generate:
    desc: chmod +x *.sh
    cmds:
      - git submodule update --init --recursive --checkout -f
      # - task: permission
      - go run main.go generate
      - go run main.go generateWorkflow
      - go run main.go generateReadme
      - git add .github/workflows/build-on-push.yml
      - git add README.md

  build:
    desc: build
    cmds:
      - go run main.go build --cache-from=false --cache-to=false --push --tag=ghcr.io/zcube/bitnami-compat --platforms=linux/amd64,linux/arm64
      # - go run main.go build --cache-from=false --cache-to=false --push --tag=ghcr.io/zcube/bitnami-compat --platforms=linux/amd64,linux/arm64 --app=bitnami-shell
      
  checkCharts:
    desc: checkCharts
    ignore_error: true
    cmds:
      - git clone https://github.com/bitnami/charts
      - go run main.go checkCharts --level=1

  list:
    desc: list
    cmds:
      - go run main.go list

  upgrade:
    desc: upgrade all bitnami submodules
    cmds:
      - git submodule update --init --recursive --checkout -f --remote
      - git add containers
      - go run main.go revisionUp
      - git add config.yaml
      - task: generate

  push:
    desc: upgrade all bitnami submodules
    cmds:
      - git submodule update --init --recursive --checkout -f --remote
      - go run main.go revisionUp
      - git add config.yaml
      # - task: generate
      - git commit -am "Update"
      - git push
