image:
  debug: true

envoy:
  service:
    ports:
      http: 81

# discourse
discourse:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5000

# mastodon
web:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5000
