name: Build on Push
on: [push]

env:
  REGISTRY: ghcr.io

jobs:
  build-bitnami-compat:
    runs-on: ubuntu-latest
    if: >-
      ${{ !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip ci]')
      }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
         - APP: "acmesolver"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "1"
           VERSION: "1.8.2"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "cainjector"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "1"
           VERSION: "1.8.2"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "cert-manager"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "1"
           VERSION: "1.8.2"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "cert-manager-webhook"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "1"
           VERSION: "1.8.2"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "consul"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "1"
           VERSION: "1.12.2"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "consul-exporter"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "0"
           VERSION: "0.8.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "elasticsearch"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "7"
           VERSION: "7.17.5"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "elasticsearch"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "8"
           VERSION: "8.3.2"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "etcd"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "3.3"
           VERSION: "3.3.27"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "etcd"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "3.4"
           VERSION: "3.4.18"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "etcd"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "3.5"
           VERSION: "3.5.4"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "fluentd"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "1"
           VERSION: "1.15.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "jmx-exporter"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "0"
           VERSION: "0.17.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "kafka"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "3.0"
           VERSION: "3.0.1"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "kafka"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "3.1"
           VERSION: "3.1.1"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "kafka"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "3.2"
           VERSION: "3.2.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "keycloak"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "18"
           VERSION: "18.0.2"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "10.5"
           VERSION: "10.5.16"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "10.6"
           VERSION: "10.6.8"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "10.7"
           VERSION: "10.7.4"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "10.8"
           VERSION: "10.8.3"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb-galera"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "10.5"
           VERSION: "10.5.16"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb-galera"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "10.6"
           VERSION: "10.6.8"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb-galera"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "10.7"
           VERSION: "10.7.4"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb-galera"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "10.8"
           VERSION: "10.8.3"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "memcached"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "1"
           VERSION: "1.6.15"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "minio"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "2022"
           VERSION: "2022.7.8"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "minio-client"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "2022"
           VERSION: "2022.7.6"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mongodb"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "4.2"
           VERSION: "4.2.21"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mongodb"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "4.4"
           VERSION: "4.4.15"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mongodb"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "5.0"
           VERSION: "5.0.9"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mysql"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "8.0"
           VERSION: "8.0.29"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mysqld-exporter"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "0"
           VERSION: "0.14.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "nginx"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "1.21"
           VERSION: "1.21.6"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "nginx"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "1.22"
           VERSION: "1.22.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "nginx"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "1.23"
           VERSION: "1.23.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgresql"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "10"
           VERSION: "10.21.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgresql"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "11"
           VERSION: "11.16.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgresql"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "12"
           VERSION: "12.11.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgresql"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "13"
           VERSION: "13.7.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgresql"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "14"
           VERSION: "14.4.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "rabbitmq"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "3.10"
           VERSION: "3.10.5"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "rabbitmq"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "3.8"
           VERSION: "3.8.34"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "rabbitmq"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "3.9"
           VERSION: "3.9.20"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "6.0"
           VERSION: "6.0.16"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "6.2"
           VERSION: "6.2.7"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "7.0"
           VERSION: "7.0.2"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-cluster"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "6.0"
           VERSION: "6.0.16"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-cluster"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "6.2"
           VERSION: "6.2.7"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-cluster"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "7.0"
           VERSION: "7.0.2"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-exporter"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "1"
           VERSION: "1.43.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-sentinel"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "6.0"
           VERSION: "6.0.16"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-sentinel"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "6.2"
           VERSION: "6.2.7"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-sentinel"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "7.0"
           VERSION: "7.0.2"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "tomcat"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "10"
           VERSION: "10.0.22"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "tomcat"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "8.5"
           VERSION: "8.5.81"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "tomcat"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "9.0"
           VERSION: "9.0.64"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "wordpress"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "5"
           VERSION: "5.9.3"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "wordpress"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "6"
           VERSION: "6.0.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "zookeeper"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "3.6"
           VERSION: "3.6.3"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "zookeeper"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "3.7"
           VERSION: "3.7.1"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "zookeeper"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "3.8"
           VERSION: "3.8.0"
           REVISION: "0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Submodule init
        shell: bash
        run: git submodule init
      - name: Checkout bitnami recipe
        shell: bash
        run: git submodule update bitnami-docker-${{ matrix.APP }}
      # - name: Checkout bitnami recipe
      #   uses: actions/checkout@v2
      #   with:
      #     repository: ${{ matrix.REPO_OWNER }}/bitnami-docker-${{ matrix.APP }}
      #     path: 'bitnami-docker-${{ matrix.APP }}'
      #     ref: master
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: repository
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          tags: |
            type=raw,value=${{ matrix.VERSION_MAJOR }}
            type=raw,value=${{ matrix.VERSION_MAJOR }}-${{ matrix.OS_FLAVOUR }}
            type=raw,value=${{ matrix.VERSION }}
            type=raw,value=${{ matrix.VERSION }}-${{ matrix.OS_FLAVOUR }}
            type=raw,value=${{ matrix.VERSION }}-${{ matrix.OS_FLAVOUR }}-r${{ matrix.REVISION }}
          images: ${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}/${{ matrix.APP }}
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Update Dockerfile OS_ARCH
        shell: bash
        run: go run main.go generate
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: bitnami-docker-${{ matrix.APP }}/${{ matrix.VERSION_MAJOR }}/${{ matrix.OS_FLAVOUR }}
          file: bitnami-docker-${{ matrix.APP }}/${{ matrix.VERSION_MAJOR }}/${{ matrix.OS_FLAVOUR }}/Dockerfile.arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}/cache/${{ matrix.APP }}:${{ matrix.VERSION }}
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}/cache/${{ matrix.APP }}:${{ matrix.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
