name: Build
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 5'
    - cron: '0 4 * * 5' # trigger for failed jobs

env:
  REGISTRY: ghcr.io

jobs:
  build-bitnami-compat:
    runs-on: ubuntu-latest
    if: >-
      ${{ !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip ci]')
      }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
         - APP: "acmesolver"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "bitnami-shell"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "cainjector"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "cert-manager"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "cert-manager-webhook"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "consul"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "consul-exporter"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "elasticsearch"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "elasticsearch-exporter"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "etcd"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "fluentd"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "jmx-exporter"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "kafka"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "kafka-exporter"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "keycloak"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "kubectl"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb-galera"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "memcached"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "memcached-exporter"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "minio"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "minio-client"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mongodb"
           OS_FLAVOUR: "debian-10"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mongodb-exporter"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mysql"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mysqld-exporter"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "nginx"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "nginx-exporter"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "pgpool"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgres-exporter"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgresql"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgresql-repmgr"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "rabbitmq"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-cluster"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-exporter"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "redis-sentinel"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "sealed-secrets"
           OS_FLAVOUR: "scratch"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "tomcat"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "wordpress"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "zookeeper"
           OS_FLAVOUR: "debian-11"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Submodule init
        shell: bash
        run: git submodule init
      - name: Checkout bitnami recipe
        shell: bash
        run: git submodule update bitnami-dockers/bitnami-docker-${{ matrix.APP }}
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: repository
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          tags: |
            type=raw,value=${{ matrix.VERSION_MAJOR }}
            type=raw,value=${{ matrix.VERSION_MAJOR }}-${{ matrix.OS_FLAVOUR }}
            type=raw,value=${{ matrix.VERSION }}
            type=raw,value=${{ matrix.VERSION }}-${{ matrix.OS_FLAVOUR }}
            type=raw,value=${{ matrix.VERSION }}-${{ matrix.OS_FLAVOUR }}-r${{ matrix.REVISION }}
          images: ${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}/${{ matrix.APP }}
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Update Dockerfile OS_ARCH
        shell: bash
        run: |
          go run main.go generate --app=${{ matrix.APP }}
          go run main.go build --app=${{ matrix.APP }} --cache-from --cache-to --push --platforms=linux/amd64,linux/arm64
