name: Build on Push
on: [push]

env:
  REGISTRY: ghcr.io

jobs:
  build-bitnami-compat:
    runs-on: ubuntu-latest
    if: >-
      ${{ !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip ci]')
      }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
         - APP: "docker-acmesolver"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-acmesolver"
           VERSION: "1.8.2"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-cainjector"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-cainjector"
           VERSION: "1.8.2"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-cert-manager"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-cert-manager"
           VERSION: "1.8.2"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-cert-manager-webhook"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-cert-manager-webhook"
           VERSION: "1.8.2"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-consul"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-consul"
           VERSION: "1.12.2"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-consul-exporter"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-consul-exporter"
           VERSION: "0.8.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-elasticsearch"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-elasticsearch"
           VERSION: "7.17.5"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-elasticsearch"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-elasticsearch"
           VERSION: "8.3.2"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-etcd"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-etcd"
           VERSION: "3.3.27"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-etcd"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-etcd"
           VERSION: "3.4.18"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-etcd"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-etcd"
           VERSION: "3.5.4"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-fluentd"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-fluentd"
           VERSION: "1.15.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-jmx-exporter"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-jmx-exporter"
           VERSION: "0.17.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-kafka"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-kafka"
           VERSION: "3.0.1"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-kafka"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-kafka"
           VERSION: "3.1.1"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-kafka"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-kafka"
           VERSION: "3.2.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-keycloak"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-keycloak"
           VERSION: "18.0.2"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-mariadb"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-mariadb"
           VERSION: "10.5.16"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-mariadb"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-mariadb"
           VERSION: "10.6.8"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-mariadb"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-mariadb"
           VERSION: "10.7.4"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-mariadb"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-mariadb"
           VERSION: "10.8.3"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-mariadb-galera"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-mariadb-galera"
           VERSION: "10.5.16"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-mariadb-galera"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-mariadb-galera"
           VERSION: "10.6.8"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-mariadb-galera"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-mariadb-galera"
           VERSION: "10.7.4"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-mariadb-galera"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-mariadb-galera"
           VERSION: "10.8.3"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-memcached"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-memcached"
           VERSION: "1.6.15"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-minio"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-minio"
           VERSION: "2022.7.8"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-minio-client"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-minio-client"
           VERSION: "2022.7.6"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-mongodb"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "bitnami-docker-mongodb"
           VERSION: "4.2.21"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-mongodb"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "bitnami-docker-mongodb"
           VERSION: "4.4.15"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-mongodb"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-mongodb"
           VERSION: "5.0.9"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-mysql"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-mysql"
           VERSION: "8.0.29"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-mysqld-exporter"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-mysqld-exporter"
           VERSION: "0.14.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-nginx"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-nginx"
           VERSION: "1.23.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-pgpool"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-pgpool"
           VERSION: "4.3.2"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-postgresql"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-postgresql"
           VERSION: "10.21.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-postgresql"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-postgresql"
           VERSION: "11.16.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-postgresql"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-postgresql"
           VERSION: "12.11.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-postgresql"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-postgresql"
           VERSION: "13.7.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-postgresql"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-postgresql"
           VERSION: "14.4.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-postgresql-repmgr"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-postgresql-repmgr"
           VERSION: "10.21.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-postgresql-repmgr"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-postgresql-repmgr"
           VERSION: "11.16.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-postgresql-repmgr"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-postgresql-repmgr"
           VERSION: "12.11.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-postgresql-repmgr"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-postgresql-repmgr"
           VERSION: "13.7.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-postgresql-repmgr"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-postgresql-repmgr"
           VERSION: "14.4.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-rabbitmq"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-rabbitmq"
           VERSION: "3.10.5"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-rabbitmq"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-rabbitmq"
           VERSION: "3.8.34"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-rabbitmq"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-rabbitmq"
           VERSION: "3.9.20"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-redis"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-redis"
           VERSION: "6.0.16"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-redis"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-redis"
           VERSION: "6.2.7"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-redis"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-redis"
           VERSION: "7.0.2"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-redis-cluster"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-redis-cluster"
           VERSION: "6.0.16"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-redis-cluster"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-redis-cluster"
           VERSION: "6.2.7"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-redis-cluster"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-redis-cluster"
           VERSION: "7.0.3"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-redis-exporter"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-redis-exporter"
           VERSION: "1.43.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-redis-sentinel"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-redis-sentinel"
           VERSION: "6.0.16"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-redis-sentinel"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-redis-sentinel"
           VERSION: "6.2.7"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-redis-sentinel"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-redis-sentinel"
           VERSION: "7.0.2"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-tomcat"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-tomcat"
           VERSION: "10.0.22"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-tomcat"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-tomcat"
           VERSION: "8.5.81"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-tomcat"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-tomcat"
           VERSION: "9.0.64"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-wordpress"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-wordpress"
           VERSION: "5.9.3"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-wordpress"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-wordpress"
           VERSION: "6.0.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-zookeeper"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-zookeeper"
           VERSION: "3.6.3"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-zookeeper"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-zookeeper"
           VERSION: "3.7.1"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "docker-zookeeper"
           OS_FLAVOUR: "debian-11"
           VERSION_MAJOR: "bitnami-docker-zookeeper"
           VERSION: "3.8.0"
           REVISION: "9"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Submodule init
        shell: bash
        run: git submodule init
      - name: Checkout bitnami recipe
        shell: bash
        run: git submodule update bitnami-dockers/bitnami-docker-${{ matrix.APP }}
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: repository
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          tags: |
            type=raw,value=${{ matrix.VERSION_MAJOR }}
            type=raw,value=${{ matrix.VERSION_MAJOR }}-${{ matrix.OS_FLAVOUR }}
            type=raw,value=${{ matrix.VERSION }}
            type=raw,value=${{ matrix.VERSION }}-${{ matrix.OS_FLAVOUR }}
            type=raw,value=${{ matrix.VERSION }}-${{ matrix.OS_FLAVOUR }}-r${{ matrix.REVISION }}
          images: ${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}/${{ matrix.APP }}
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Update Dockerfile OS_ARCH
        shell: bash
        run: go run main.go generate
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: bitnami-dockers/bitnami-docker-${{ matrix.APP }}/${{ matrix.VERSION_MAJOR }}/${{ matrix.OS_FLAVOUR }}
          file: bitnami-dockers/bitnami-docker-${{ matrix.APP }}/${{ matrix.VERSION_MAJOR }}/${{ matrix.OS_FLAVOUR }}/Dockerfile.arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}/cache/${{ matrix.APP }}:${{ matrix.VERSION }}
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}/cache/${{ matrix.APP }}:${{ matrix.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
