name: Build on Push
on: [push]

env:
  REGISTRY: ghcr.io

jobs:
  build-bitnami-compat:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
         - APP: "etcd"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "3"
           VERSION: "3.5.1-3"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "bitnami-shell"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10"
           VERSION: "10"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "consul"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "1"
           VERSION: "1.11.2"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
        #  - APP: "mysql"
        #    OS_FLAVOUR: "debian-10"
        #    VERSION_MAJOR: "8.0"
        #    VERSION: "8.0.28"
        #    OS_NAME: "linux"
        #    REPO_OWNER: "bitnami"
         - APP: "postgresql"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10"
           VERSION: "10.19.0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgresql"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "11"
           VERSION: "11.14.0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgresql"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "12"
           VERSION: "12.9.0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgresql"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "13"
           VERSION: "13.5.0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "postgresql"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "14"
           VERSION: "14.1.0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10.3"
           VERSION: "10.3.32"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10.4"
           VERSION: "10.4.22"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10.5"
           VERSION: "10.5.13"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mariadb"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "10.6"
           VERSION: "10.6.5"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "rabbitmq"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "3.9"
           VERSION: "3.9.13"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "minio"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "2022"
           VERSION: "2022.1.8"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "minio-client"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "2022"
           VERSION: "2022.1.25"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "mysqld-exporter"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "0"
           VERSION: "0.13.0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "consul-exporter"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "0"
           VERSION: "0.7.1"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "cert-manager"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "1"
           VERSION: "1.7.0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "cert-manager-webhook"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "1"
           VERSION: "1.7.0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "acmeresolver"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "1"
           VERSION: "1.7.0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
         - APP: "cainjector"
           OS_FLAVOUR: "debian-10"
           VERSION_MAJOR: "1"
           VERSION: "1.7.0"
           OS_NAME: "linux"
           REPO_OWNER: "bitnami"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout bitnami recipe
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.REPO_OWNER }}/bitnami-docker-${{ matrix.APP }}
          path: 'bitnami-docker-${{ matrix.APP }}'
          ref: master
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.APP }}
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Update Dockerfile OS_ARCH
        shell: bash
        run: ./scripts/update.sh
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: string
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: bitnami-docker-${{ matrix.APP }}/${{ matrix.VERSION_MAJOR }}/${{ matrix.OS_FLAVOUR }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ matrix.VERSION_MAJOR }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}-${{ matrix.VERSION_MAJOR }}-build-cache
          cache-to: type=registry,ref=${{ steps.meta.outputs.tags }}-${{ matrix.VERSION_MAJOR }}-build-cache
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}
            BASE_TAG=${{ steps.extract_branch.outputs.branch }}
