name: Squash
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  squash:
    runs-on: ubuntu-latest
    if: >-
      ${{ !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip ci]')
      }}
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Submodule init
        shell: bash
        run: git submodule init
      - name: Checkout bitnami recipe
        shell: bash
        run: git submodule update charts
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install docker-squash
      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: install crane and login
        run: |
          if ! hash crane 2>/dev/null
          then
            if [[ "$OSTYPE" == "linux-gnu"* ]]; then
              OS=Linux
            elif [[ "$OSTYPE" == "darwin"* ]]; then
              OS=Darwin
            else
              OS=Unknown
            fi
            ARCH=""
            case $(uname -m) in
              x86_64)  ARCH="x86_64" ;;
              aarch64) ARCH="arm64" ;;
            esac
          
            echo ${OS}_${ARCH}
          
            mkdir -p /tmp/go-containerregistry
            cd /tmp/go-containerregistry
            curl -o go-containerregistry.tar.gz -sL "https://github.com/google/go-containerregistry/releases/latest/download/go-containerregistry_${OS}_${ARCH}.tar.gz"
            tar zxvf go-containerregistry.tar.gz
            cp -f crane /usr/local/bin/crane
            cp -f gcrane /usr/local/bin/gccrane
            cp -f krane /usr/local/bin/krane
            cd -
          fi
      - name: login
        shell: bash
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | crane auth login ghcr.io --username "dummy" --password-stdin
      - name: Squash
        shell: bash
        run: ./scripts/squash.sh
